title: "sudo dream"
info: blog and other things
desc: Hi, as you may have noticed from the header, my name is Moustafa. I work as a software engineer (or at least this is what people think).
owner: I am Moustafa
email: 

menu:

github:
linkedin:
twitter:
instagram: 
stackoverflow: